baseURL = "https://pagwin.xyz"
languageCode = "en-us"
title = "Pagwin's website"
theme = "liquorice"

[params]
    author = "Pagwin"

[menu]
    [[menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/blog/"
    [[menu.main]]
        identifier = "github"
        name = "github"
        url = "https://github.com/Pagwin-Fedora"
    [[menu.main]]
        identifier = "monies"
        name = "gib monies"
        url = "/monies/"
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true
