baseURL = "https://pagwin.xyz"
languageCode = "en-us"
title = "Pagwin's website"
theme = "liquorice"

[params]
    author = "Pagwin"

[menu]
    [[menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/blog/"
    [[menu.main]]
	identifier = "links"
	name = "links"
	url = "/links/"
    [[menu.main]]
	parent = "links"
        identifier = "github"
        name = "github"
        url = "https://github.com/Pagwin-Fedora"
    [[menu.main]]
	parent = "links"
        identifier = "linkedin"
        name = "linkedin"
        url = "https://www.linkedin.com/in/spencer-powell-pagwin/"
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true

[security]
    [security.funcs]
	# first 2 vars are things hugo has built in and I'm keeping to avoid breakage
	getenv = ['^HUGO_', '^CI$', "COMMENTS_BACKEND"]
