version: "3"
# copied from the docker-compose I wrote specifically for the comments backend which was made referencing the invidious docker compose file which was very helpful https://github.com/iv-org/invidious/blob/master/docker-compose.yml
services:
  website:
    image: ghcr.io/pagwin-fedora/website_frontend:latest-comments
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - comments_backend
  # need to specifically name it this unless you want to build the docker image in place
  comments_backend:
    image: ghcr.io/pagwin-fedora/comments_backend
    restart: unless-stopped
    environment:
      DB_URI: comments-db
      DB_PORT: 5432
      DB_USER: kemal
      DB_PASSWORD: kemal
      DB_NAME: comments
      DB_SSL: disable
    depends_on:
      - comments-db
  comments-db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: comments
      # yes I'm stealing the invidious postgres user
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
volumes:
  postgresdata:
